server:
  port: 8080

spring:
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

worldnews:
  base-url: https://api.worldnewsapi.com
  api-key: ${WORLDNEWS_API_KEY:}